  - platform: ads1115
    name: "Fridge CT AC Voltage (0x48_A0_GND)"
    multiplexer: 'A0_GND'
    gain: 2.048
    ads1115_id: ads1115_bus_0x48
    update_interval: 10s
    accuracy_decimals: 4
    state_class: measurement
    device_class: voltage
    unit_of_measurement: "V"
    id: ac_v_fridge_adc_sensor
    filters:
      - throttle: 30s
  
  - platform: ct_clamp
    name: "Fridge AC Current"
    sensor: ac_v_fridge_adc_sensor
    accuracy_decimals: 2
    sample_duration: 200ms
    update_interval: 10s
    state_class: measurement
    device_class: current
    unit_of_measurement: "A"
    id: ac_a_fridge_ct_sensor
    filters:
      - calibrate_linear:
          # Linear mapping for calculated Amps AC to real Amps AC on the wire
          - 0.0750 -> 0.135
          - 0.2950 -> 4.070
      - throttle: 30s
  
  #### Template to also publish calculated power measured (using 230 V)
  - platform: template
    name: "Fridge AC Power"
    lambda: |-
      if ( id(ac_a_fridge_ct_sensor).state < 0 ) {
        return 0;
      } else {
        return (230 * id(ac_a_fridge_ct_sensor).state);
      }
    accuracy_decimals: 1
    update_interval: 30s
    state_class: measurement
    device_class: power
    unit_of_measurement: "W"
    id: ac_power_fridge
  
  - platform: total_daily_energy
    name: "Fridge Energy Consumed"
    power_id: ac_power_fridge
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001
  
  - platform: homeassistant
    name: "Measured AC Voltage"
    entity_id: sensor.ac_voltage
    attribute: voltage
    unit_of_measurement: "V"
    device_class: temperature
    accuracy_decimals: 1
    id: ha_ac_voltage
    filters:
      - offset: 12.0

#    lambda: |-
#      if ( id(ha_ac_voltage).state < 0 ) {
#        return 0;
#      } else {
#        return (id(ha_ac_voltage) * id(ac_a_fridge_ct_sensor).state);
#      }
