# Hostname : esp32-02
# Friendly Name : power-monitoring
# Summary : Multi channel AC power monitoring for home electrical circuits
# Description : By using SCT-013 CT clamps with 1 V AC output and external ADS1115 ADC, 
#               measure per-circuit AC current for instantaneous and cumulative energy utilization
# Software Used : Latest ESPHome code with two 4-channel ADS1115 ADC 16-bit boards attached to separate I2C buses
#   https://esphome.io/devices/esp32.html
#   https://esphome.io/components/i2c.html
#   https://esphome.io/components/sensor/adc.html
#   https://esphome.io/components/sensor/ct_clamp.html
#
# This is the list of electrical circuits to be monitored (current and voltage are AC)
# 1. Frigorífico    :  5 A / 1 V SCT-013 #1
# 
# 2. Iluminación    : 15 A / 1 V SCT-013 #1
#    Lavadora       :
# 
# 3. Telecom.       :
#    Sensores       :  5 A / 1 V SCT-013 #2
#    Ventilación    :
# 
# 4. Fuerza Seco    : 10 A / 1 V SCT-013 #1
# 
# 5. Fuerza Húmedo  : 
#    Horno          : 30 A / 1 V SCT-013 #1
#    Domótica       :
# 
# 6. Inducción      : 30 A / 1 V SCT-013 #2
#    Lavavajillas   : 
# 
# 7. Bajo Cubierta :  5 A / 1 V SCT-013 #3
# 
# 8. Bajo Vivienda : 10 A / 1 V SCT-013 #2
#
# Last Modified : 2022-01-15
#

esphome:
  name: power-monitoring
  comment: "Home Power Monitoring"
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret home_ssid
  password: !secret home_ssid_password
  power_save_mode: none
  fast_connect: on
  use_address: 192.168.1.170
  manual_ip:
    static_ip: 192.168.1.170
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.100
    dns2: 192.168.1.10
  ap:
    ssid: "HOME_POWER_MONITORING"
    password: !secret esp_ap_password

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Madrid"

captive_portal:

logger:
  level: VERBOSE

api:
  password: !secret esphome_api_password

ota:
  safe_mode: True
  password: !secret esphome_ota_password

web_server:
  port: 8888
  auth:
    username: !secret esphome_web_server_username
    password: !secret esphome_web_server_password

mqtt:
  broker: 192.168.1.100
  port: 1883
  discovery: True
  discovery_retain: True
  discovery_prefix: "homeassistant"
  topic_prefix: home/indoors/mechanical_room/home_power_monitoring


# Create single I2C bus where both ADS1115 at addresses 0x48 and 0x49 will be used and
# instantiate the two ADC boards (hubs) at their corresponding addresses
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 50kHz
  id: i2c_bus

ads1115:
  - address: 0x48
    continuous_mode: off
    id: ads1115_bus_0x48

  - address: 0x49
    continuous_mode: off
    id: ads1115_bus_0x49


# Board monitoring and power cycling
switch:
  - platform: restart
    name: "Home Power Monitoring Restart"

binary_sensor:
  - platform: status
    name: "Home Power Monitoring Status"

sensor:
  - platform: wifi_signal
    name: "Home Power Monitoring WiFi Level"
    update_interval: 60s

####  - platform: homeassistant
####    name: "Measured AC Voltage"
####    entity_id: sensor.ac_voltage
####    attribute: voltage
####    unit_of_measurement: "V"
####    device_class: voltage
####    accuracy_decimals: 1
####    id: ha_ac_voltage
####    filters:
####      - offset: 12.0

#### Sensor definitions for each of the monitored circuits in separate files for readability

# 1. FRIDGE (ADS1115 0x48 , A0_GND)
  - platform: ads1115
    name: "Fridge CT AC Voltage (0x48_A0_GND)"
    multiplexer: 'A0_GND'
    gain: 2.048
    ads1115_id: ads1115_bus_0x48
    update_interval: 10s
    accuracy_decimals: 4
    state_class: measurement
    device_class: voltage
    unit_of_measurement: "V"
    id: ac_v_fridge_adc_sensor
    filters:
      - throttle: 30s
  
  - platform: ct_clamp
    name: "Fridge AC Current"
    sensor: ac_v_fridge_adc_sensor
    accuracy_decimals: 2
    sample_duration: 1000ms
    update_interval: 10s
    state_class: measurement
    device_class: current
    unit_of_measurement: "A"
    id: ac_a_fridge_ct_sensor
    filters:
      - calibrate_polynomial:
          degree: 2
          datapoints:
            - 0.005 -> 0.000
            - 0.027 -> 0.145
            - 1.200 -> 4.220
      - throttle: 30s
  
  - platform: template
    name: "Fridge AC Power"
    lambda: |-
      if ( id(ac_a_fridge_ct_sensor).state < 0 ) {
        return 0;
      }
      return ( abs(230.0 * id(ac_a_fridge_ct_sensor).state) );
    accuracy_decimals: 1
    update_interval: 30s
    state_class: measurement
    device_class: power
    unit_of_measurement: "W"
    id: ac_power_fridge
  
  - platform: total_daily_energy
    name: "Fridge Energy Consumed"
    power_id: ac_power_fridge
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001
  

# 2. LIGHTING + WASHING MACHINE (ADS1115 0x48, A1_GND)
  - platform: ads1115
    name: "Lighting Washing CT AC Voltage (0x48_A1_GND)"
    multiplexer: 'A1_GND'
    gain: 2.048
    ads1115_id: ads1115_bus_0x48
    update_interval: 10s
    accuracy_decimals: 4
    state_class: measurement
    device_class: voltage
    unit_of_measurement: "V"
    id: ac_v_lighting_adc_sensor
    filters:
      - throttle: 30s
  
  - platform: ct_clamp
    name: "Lighting Washing AC Current"
    sensor: ac_v_lighting_adc_sensor
    accuracy_decimals: 2
    sample_duration: 1000ms
    update_interval: 10s
    state_class: measurement
    device_class: current
    unit_of_measurement: "A"
    id: ac_a_lighting_ct_sensor
    filters:
      - calibrate_polynomial:
          degree: 2
          datapoints:
            - 0.002 -> 0.000
            - 0.009 -> 0.145
            - 0.260 -> 4.160
            - 0.965 -> 8.000
      - throttle: 30s
  
  - platform: template
    name: "Lighting Washing AC Power"
    lambda: |-
      if ( id(ac_a_lighting_ct_sensor).state < 0 ) {
        return 0;
      }
      return ( abs(230.0 * id(ac_a_lighting_ct_sensor).state) );
    accuracy_decimals: 1
    update_interval: 30s
    state_class: measurement
    device_class: power
    unit_of_measurement: "W"
    id: ac_power_lighting
  
  - platform: total_daily_energy
    name: "Lighting Washing Energy Consumed"
    power_id: ac_power_lighting
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001


####  - platform: !include 0x48_a1_lighting.conf
##### 3. TELECOM + SENSORS + MVHR (ADS1115 0x48, A2_GND)
####  - platform: !include 0x48_a2_telecom.conf
##### 4. POWER DRY (ADS1115 0x48, A3_GND)
####  - platform: !include 0x48_a3_powerdry.conf
####
##### 5. POWER DAMP + OVEN (ADS1115 0x49, A0_GND)
####  - platform: !include 0x49_a0_powerdamp.conf
##### 6. INDUCTION HOB + DISHWASHER (ADS1115 0x49, A1_GND)
####  - platform: !include 0x49_a1_induction.conf
##### 7. ATTIC (ADS1115 0x49, A2_GND)
####  - platform: !include 0x49_a2_attic.conf
##### 8. BASEMENT (ADS1115 0x49, A3_GND)
####  - platform: !include 0x49_a3_basement.conf

